-- MySQL Script generated by MySQL Workbench
-- 04/20/17 13:49:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema helirep
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema helirep
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `helirep` DEFAULT CHARACTER SET utf8 ;
USE `helirep` ;

-- -----------------------------------------------------
-- Table `helirep`.`tbl_rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `helirep`.`tbl_rol` ;

CREATE TABLE IF NOT EXISTS `helirep`.`tbl_rol` (
  `id_rol` INT NOT NULL,
  `rol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `helirep`.`tbl_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `helirep`.`tbl_usuario` ;

CREATE TABLE IF NOT EXISTS `helirep`.`tbl_usuario` (
  `id_usuario` INT NOT NULL,
  `fk_id_rol` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `documento` VARCHAR(45) NOT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_tbl_usuario_tbl_rol1_idx` (`fk_id_rol` ASC),
  CONSTRAINT `fk_tbl_usuario_tbl_rol1`
    FOREIGN KEY (`fk_id_rol`)
    REFERENCES `helirep`.`tbl_rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `helirep`.`tbl_categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `helirep`.`tbl_categoria` ;

CREATE TABLE IF NOT EXISTS `helirep`.`tbl_categoria` (
  `id_categoria` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria`),
  UNIQUE INDEX `descripcion_UNIQUE` (`descripcion` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `helirep`.`tbl_proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `helirep`.`tbl_proveedor` ;

CREATE TABLE IF NOT EXISTS `helirep`.`tbl_proveedor` (
  `id_proveedor` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `helirep`.`tbl_material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `helirep`.`tbl_material` ;

CREATE TABLE IF NOT EXISTS `helirep`.`tbl_material` (
  `id_material` INT NOT NULL,
  `fk_id_categoria` INT NOT NULL,
  `fk_id_proveedor` INT NOT NULL,
  `referencia` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NULL,
  PRIMARY KEY (`id_material`),
  INDEX `fk_tbl_producto_tbl_categoria_idx` (`fk_id_categoria` ASC),
  INDEX `fk_tbl_producto_tbl_proveedor1_idx` (`fk_id_proveedor` ASC),
  CONSTRAINT `fk_tbl_producto_tbl_categoria`
    FOREIGN KEY (`fk_id_categoria`)
    REFERENCES `helirep`.`tbl_categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_producto_tbl_proveedor1`
    FOREIGN KEY (`fk_id_proveedor`)
    REFERENCES `helirep`.`tbl_proveedor` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `helirep`.`tbl_bodega`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `helirep`.`tbl_bodega` ;

CREATE TABLE IF NOT EXISTS `helirep`.`tbl_bodega` (
  `id_bodega` INT NOT NULL,
  `fk_id_usuario` INT NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_bodega`),
  INDEX `fk_tbl_bodega_tbl_usuario1_idx` (`fk_id_usuario` ASC),
  CONSTRAINT `fk_tbl_bodega_tbl_usuario1`
    FOREIGN KEY (`fk_id_usuario`)
    REFERENCES `helirep`.`tbl_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `helirep`.`tbl_proyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `helirep`.`tbl_proyecto` ;

CREATE TABLE IF NOT EXISTS `helirep`.`tbl_proyecto` (
  `id_proyecto` INT NOT NULL,
  `fk_id_usuario` INT NOT NULL,
  `descripcion` TEXT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NULL,
  PRIMARY KEY (`id_proyecto`),
  INDEX `fk_tbl_proyecto_tbl_usuario1_idx` (`fk_id_usuario` ASC),
  CONSTRAINT `fk_tbl_proyecto_tbl_usuario1`
    FOREIGN KEY (`fk_id_usuario`)
    REFERENCES `helirep`.`tbl_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `helirep`.`tbl_solicitud`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `helirep`.`tbl_solicitud` ;

CREATE TABLE IF NOT EXISTS `helirep`.`tbl_solicitud` (
  `id_solicitud` INT NOT NULL,
  `fk_id_proyecto` INT NOT NULL,
  `fecha_solicitud` DATE NULL,
  `tipo_movimiento` ENUM('Entregado', 'Devolución') NOT NULL,
  PRIMARY KEY (`id_solicitud`),
  INDEX `fk_tbl_solicitud_tbl_proyecto1_idx` (`fk_id_proyecto` ASC),
  CONSTRAINT `fk_tbl_solicitud_tbl_proyecto1`
    FOREIGN KEY (`fk_id_proyecto`)
    REFERENCES `helirep`.`tbl_proyecto` (`id_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `helirep`.`tbl_inventario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `helirep`.`tbl_inventario` ;

CREATE TABLE IF NOT EXISTS `helirep`.`tbl_inventario` (
  `fk_id_bodega` INT NOT NULL,
  `fk_id_material` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `fehca_actualizacion` DATE NOT NULL,
  `tipo_movimiento` ENUM('Entrada', 'Salida') NOT NULL,
  INDEX `fk_tbl_inventario_tbl_producto1_idx` (`fk_id_material` ASC),
  CONSTRAINT `fk_tbl_inventario_tbl_bodega1`
    FOREIGN KEY (`fk_id_bodega`)
    REFERENCES `helirep`.`tbl_bodega` (`id_bodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_inventario_tbl_producto1`
    FOREIGN KEY (`fk_id_material`)
    REFERENCES `helirep`.`tbl_material` (`id_material`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `helirep`.`tbl_menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `helirep`.`tbl_menu` ;

CREATE TABLE IF NOT EXISTS `helirep`.`tbl_menu` (
  `id_menu` INT NOT NULL,
  `nombre_menu` VARCHAR(45) NOT NULL,
  `url` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_menu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `helirep`.`tbl_menu_rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `helirep`.`tbl_menu_rol` ;

CREATE TABLE IF NOT EXISTS `helirep`.`tbl_menu_rol` (
  `fk_id_menu` INT NOT NULL,
  `fk_id_rol` INT NOT NULL,
  INDEX `fk_tbl_menu_has_tbl_rol_tbl_rol1_idx` (`fk_id_rol` ASC),
  INDEX `fk_tbl_menu_has_tbl_rol_tbl_menu1_idx` (`fk_id_menu` ASC),
  CONSTRAINT `fk_tbl_menu_has_tbl_rol_tbl_menu1`
    FOREIGN KEY (`fk_id_menu`)
    REFERENCES `helirep`.`tbl_menu` (`id_menu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_menu_has_tbl_rol_tbl_rol1`
    FOREIGN KEY (`fk_id_rol`)
    REFERENCES `helirep`.`tbl_rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `helirep`.`tbl_pagina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `helirep`.`tbl_pagina` ;

CREATE TABLE IF NOT EXISTS `helirep`.`tbl_pagina` (
  `id_pagina` INT NOT NULL,
  `fk_id_menu` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `url` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_pagina`),
  INDEX `fk_tbl_pagina_tbl_menu1_idx` (`fk_id_menu` ASC),
  CONSTRAINT `fk_tbl_pagina_tbl_menu1`
    FOREIGN KEY (`fk_id_menu`)
    REFERENCES `helirep`.`tbl_menu` (`id_menu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `helirep`.`tbl_material_solicitud`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `helirep`.`tbl_material_solicitud` ;

CREATE TABLE IF NOT EXISTS `helirep`.`tbl_material_solicitud` (
  `fk_id_material` INT NOT NULL,
  `fk_id_solicitud` INT NOT NULL,
  `cantidad` INT NULL,
  INDEX `fk_tbl_material_has_tbl_solicitud_tbl_solicitud1_idx` (`fk_id_solicitud` ASC),
  INDEX `fk_tbl_material_has_tbl_solicitud_tbl_material1_idx` (`fk_id_material` ASC),
  CONSTRAINT `fk_tbl_material_has_tbl_solicitud_tbl_material1`
    FOREIGN KEY (`fk_id_material`)
    REFERENCES `helirep`.`tbl_material` (`id_material`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_material_has_tbl_solicitud_tbl_solicitud1`
    FOREIGN KEY (`fk_id_solicitud`)
    REFERENCES `helirep`.`tbl_solicitud` (`id_solicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
